# Attempting Hardcoded Neurons

In [2]:
import matplotlib.pyplot as plt
import numpy as np

In [3]:
inputs = [1,2,3]
weights = [.2, .8, -.5]
bias = 2

In [4]:
output = (inputs[0] * weights[0] +
           inputs[1] * weights[1] +
           inputs[2] * weights[2] + bias)

In [5]:
print(output)

2.3


In [6]:
inputs = [1,2,3,2.5]
weights = [[.2, .8, -.5, 1],
           [.5, - .91, .26, -.5],
           [-.26, -.27, .17, .87]]

bias = [2, 3, 0.5]

# Output of current layer
layer_outputs = []
# For each neuron
for neuron_weights, neuron_bias in zip(weights, bias):
    #ensuring output is zeroed
    neuron_output = 0
    for n_input, weight in zip(inputs, neuron_weights):
        # Multiply input by weight and add to output
        neuron_output += n_input * weight
    # Add bias to output for neuron
    neuron_output += neuron_bias
    # Output neuron output
    layer_outputs.append(neuron_output)

In [7]:
print (layer_outputs)

[4.8, 1.21, 2.385]


What is a tensor: A tensor is an object that can be represented as an array but tensors are not **just** arrays

What is a dot product:
The sum of products of consecutive vector elements

In [8]:
# Example of a dot product

a = [1,2,3]
b = [2,3,4]

dot_product = a[0]*b[0] + a[1]*b[1] + a[2]*b[2]
print(dot_product)

# What happens if we call a "inputs" and b "weights"

20


If we consider the comment above now we can see that dot products seems like an easier way to perform the operations we did above to "run" our neural network

# Neurons with NumPy now

In [9]:
inputs = [1,2,3,2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2

outputs = np.dot(weights, inputs) + bias
print(outputs)

# This is for a single neuron so there is only one bias value

4.8


In [10]:
# Layer of neurons

inputs = [1,2,3,2.5]
weights = [[.2, .8, -.5, 1],
           [.5, - .91, .26, -.5],
           [-.26, -.27, .17, .87]]

bias = [2, 3, 0.5]

# This addition only works for np arrays
# With normal arrays it becoms concatenated
layer_outputs = np.dot(weights, inputs) + bias

# exploring how np.dot output looks

# print(np.dot(weights, inputs))

print(layer_outputs)

[4.8   1.21  2.385]


for the inputs the shape would be: (4, ) and the type would be a 1D array/Vector.

What would dot product on a Matrix (2D array) be? Matrix Multiplication

Transposition (written as a T superscript) modifies any vector/matrix so that the rows become columns and the columns become rows

In [16]:
a1 = np.array([[1,2,3]])
# The double bracket is to make this a matrix that contains a single row

a2 = [1,2,3]
np.array([a2])
# Same as a1

a3 = [1,2,3]
np.expand_dims(a3, axis=0)
# np.expand_dims() adds a new dimension at the index of the axis

array([[1, 2, 3]])

In [20]:
a = [1,2,3]
b = [2,3,4]

a = np.array(a)
b = np.array(b).T

np.dot(a,b)

# Is the same as
# [1,2,3] * [2,
#           3,
#           4]
#           = 1*2 + 2*3 + 3*4 = 20



20

Have to make sure that the dimensions match for inputs and weights

example:

In [22]:
inputs = [[1.0,2.0,3.0,2.5],
          [2.0,5.0,-1.0,2.0],
          [-1.5,2.7,3.3,-0.8]]
weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91,.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

outputs = np.dot(inputs,np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Our first parameter for np.dot will be our inputs then the second parameter would be our transposed weights. This is why even if we pass in a list of inputs we have a list of predictions even if there is only one prediction.